paths:
  /mobile/config/check-version:
    get:
      tags: [MOBILE]
      summary: Versiyani tekshirish
      parameters:
        - name: platform
          in: query
          schema: { type: string, enum: [android, ios] }
        - name: version
          in: query
          schema: { type: string }
      responses:
        200: { description: OK }