paths:
  /mobile/config/check-version:
    get:
      tags: [MOBILE]
      summary: Versiyani tekshirish
      responses:
        200:
          description: OK
  /mobile/health:
    get:
      tags: [MOBILE]
      summary: Health check
      responses:
        200:
          description: OK